
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
      path: "prisma/migrations",
      //From Prisma v7, location of seeding file apparently needs to be indicated here instead of the package.json file. Source: terminal warnings and https://www.prisma.io/docs/orm/prisma-migrate/workflows/seeding
      //From Prisma v7, in tsconfig.json, in key "compilerOptions", "ignoreDeprecations": "6.0" apparently needs to be added for ES-module (ESM) compatibility. Source: https://www.prisma.io/docs/getting-started/prisma-orm/quickstart/mysql
    },
    engine: "classic",
    datasource: {
      url: env("DATABASE_URL"),
    },
});
